# Generated by Django 5.2.6 on 2025-09-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='localidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='logradouro',
            new_name='rua',
        ),
    ]
