# Generated by Django 5.2.6 on 2025-09-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_rename_localidade_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='cidade',
            new_name='localidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='logradouro',
        ),
    ]
